(()=>{
'use strict';
const qs=new URLSearchParams(location.search);
let room=qs.get('room');
if(!room){room=(crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random().toString(36)).replace(/-/g,'');qs.set('room',room);history.replaceState(null,'',location.pathname+'?'+qs.toString())}
const V1=`trip-a-trip/v1/${room}`,V2=`trip-a-trip/v2/${room}`,BROKER='wss://broker.emqx.io:8084/mqtt';
const nativeMode=qs.get('native')==='1';
const rid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const viewerId=localStorage.getItem('tat-viewer-id')||rid();localStorage.setItem('tat-viewer-id',viewerId);
const webDeviceId=localStorage.getItem(`tat-device-${room}`)||rid();localStorage.setItem(`tat-device-${room}`,webDeviceId);
let myName=qs.get('name')||localStorage.getItem(`tat-name-${room}`)||'';
let role=qs.get('role')||localStorage.getItem(`tat-role-${room}`)||'watch';
if(myName)localStorage.setItem(`tat-name-${room}`,myName);if(qs.get('role'))localStorage.setItem(`tat-role-${room}`,role);
let tracking=false,watchId=null,lastPublished=null,lastPublishAt=0,pendingWaypoint=false,pendingMissionId=null,currentWaypointId=null,timelineLive=true,selectedTs=Date.now(),currentTab='now',weatherCache={ts:0,key:'',data:null},postcardBlob=null;
let myTrail=[];try{myTrail=JSON.parse(localStorage.getItem(`tat-trail-${room}-${webDeviceId}`)||'[]')}catch(e){}if(!Array.isArray(myTrail))myTrail=[];
const members=new Map(),events=new Map(),waypoints=new Map(),reactions=new Map(),comments=new Map(),presence=new Map(),missions=new Map(),photoMarkers=new Map(),wpMarkers=new Map();
const $=id=>document.getElementById(id);
const els={room:$('roomLabel'),watchers:$('watchers'),dot:$('brokerDot'),broker:$('brokerText'),weather:$('weatherBadge'),nowTitle:$('nowTitle'),nowSubtitle:$('nowSubtitle'),nowStats:$('nowStats'),target:$('currentTarget'),people:$('people'),quick:$('quickRow'),photo:$('photoBtn'),feedPhoto:$('feedPhotoBtn'),photoInput:$('photoInput'),checkin:$('checkinBtn'),track:$('trackBtn'),sos:$('sosBtn'),latest:$('latestMoment'),missionPreview:$('missionPreview'),fit:$('fitBtn'),liveMap:$('liveMapBtn'),timeRange:$('timeRange'),timeLabel:$('timeLabel'),timelineLive:$('timelineLiveBtn'),feed:$('feed'),feedCount:$('feedCount'),comment:$('commentInput'),commentBtn:$('commentBtn'),wpHint:$('waypointHint'),waypointBtn:$('waypointBtn'),wps:$('waypoints'),missionInput:$('missionInput'),missionBtn:$('missionBtn'),missions:$('missions'),days:$('days'),postcardBtn:$('postcardBtn'),daysPostcard:$('daysPostcardBtn'),join:$('joinModal'),name:$('nameInput'),joinTravel:$('joinTravel'),joinWatch:$('joinWatch'),postcardModal:$('postcardModal'),postcardPreview:$('postcardPreview'),postcardClose:$('postcardClose'),postcardShare:$('postcardShare'),postcardSave:$('postcardSave'),share:$('shareBtn'),toast:$('toast')};
els.room.textContent='комната '+room.slice(0,8);
if(myName){els.name.value=myName;els.join.classList.remove('show')}else els.join.classList.add('show');

const map=L.map('map',{zoomControl:false,attributionControl:true}).setView([45.45,25.5],8);L.control.zoom({position:'topright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);
const palette=['#38bdf8','#fb7185','#a78bfa','#4ade80','#facc15','#fb923c','#2dd4bf','#e879f9'];
function colorFor(id){let h=0;for(const c of id||'x')h=((h<<5)-h)+c.charCodeAt(0);return palette[Math.abs(h)%palette.length]}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmtAge(ts){const s=Math.max(0,Math.floor((Date.now()-(ts||0))/1000));return s<10?'сейчас':s<60?s+'с назад':s<3600?Math.floor(s/60)+'м назад':Math.floor(s/3600)+'ч назад'}
function fmtTime(ts){return new Date(ts).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}
function fmtClock(ts){return new Date(ts).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}
function dayKey(ts){const d=new Date(ts);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function prettyDay(key){const d=new Date(key+'T12:00:00');return d.toLocaleDateString('ru-RU',{weekday:'long',day:'numeric',month:'long'})}
function km(m){if(!Number.isFinite(m))return '—';return m<1000?Math.round(m)+' м':(m/1000).toFixed(m<10000?1:0)+' км'}
function dist(a,b){if(!a||!b)return Infinity;const R=6371e3,p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dp=(b.lat-a.lat)*Math.PI/180,dl=(b.lng-a.lng)*Math.PI/180,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function trailDistance(tr){let n=0;for(let i=1;i<tr.length;i++){const d=dist(tr[i-1],tr[i]);if(Number.isFinite(d)&&d<5000)n+=d}return n}
function ascent(tr){let a=0;for(let i=1;i<tr.length;i++){const x=tr[i-1].altitude,y=tr[i].altitude;if(Number.isFinite(x)&&Number.isFinite(y)&&y>x&&y-x<250)a+=y-x}return a}
function toast(t){els.toast.textContent=t;els.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.remove('show'),1900)}
function setBroker(ok,text){els.dot.className=ok===true?'on':ok===false?'err':'';els.broker.textContent=text}
function publish(topic,obj,retain=true){if(!client.connected){toast('Нет связи с live-каналом');return false}client.publish(topic,JSON.stringify(obj),{qos:0,retain});return true}
function freshestMember(){return [...members.values()].filter(m=>m.payload).sort((a,b)=>(b.payload.ts||0)-(a.payload.ts||0))[0]?.payload||null}
function myMember(){const same=[...members.values()].map(m=>m.payload).filter(Boolean).find(p=>myName&&p.name===myName);return same||members.get(webDeviceId)?.payload||null}
function currentPos(){return myMember()?.pos||freshestMember()?.pos||null}
function motionLabel(pos){const k=Number.isFinite(pos?.speed)?pos.speed*3.6:0;return k>25?'едет':k>7?'бежит':k>1.5?'идёт':'на месте'}
function currentTargetObj(){return currentWaypointId?waypoints.get(currentWaypointId):null}
function eventArray(){return [...events.values(),...comments.values()].filter(Boolean).sort((a,b)=>(b.ts||0)-(a.ts||0))}
function photoEvents(){return [...events.values()].filter(e=>e.type==='photo').sort((a,b)=>b.ts-a.ts)}

function switchTab(tab){currentTab=tab;document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${tab}`));document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));if(tab==='map')setTimeout(()=>map.invalidateSize(),80);if(tab==='days')renderDays()}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));

function memberPosAt(p,ts){const tr=(p.trail||[]).filter(x=>(x.ts||0)<=ts);if(tr.length)return tr[tr.length-1];return (p.ts||0)<=ts?p.pos:null}
function upsertMember(p){if(!p?.id||!p?.pos)return;let m=members.get(p.id),c=colorFor(p.id);if(!m){m={color:c,line:L.polyline([],{color:c,weight:4,opacity:.86}).addTo(map),dot:L.circleMarker([p.pos.lat,p.pos.lng],{radius:9,color:'#fff',weight:3,fillColor:c,fillOpacity:1}).addTo(map)};m.dot.bindTooltip(p.name||'Участник',{permanent:true,direction:'top',offset:[0,-10],className:'member-tip'});members.set(p.id,m)}m.payload=p;m.dot.setTooltipContent(p.name||'Участник');renderAll();maybeWeather()}
function renderTimelineMap(){const ts=timelineLive?Date.now():selectedTs;members.forEach(m=>{const p=m.payload,pts=(p.trail||[]).filter(x=>(x.ts||0)<=ts).map(x=>[x.lat,x.lng]);m.line.setLatLngs(pts);const at=memberPosAt(p,ts);if(at){m.dot.setLatLng([at.lat,at.lng]);m.dot.setStyle({opacity:1,fillOpacity:1})}else m.dot.setStyle({opacity:0,fillOpacity:0})});events.forEach((e,id)=>{if(e.type!=='photo'||!Number.isFinite(e.lat)||!Number.isFinite(e.lng))return;let mk=photoMarkers.get(id);if(!mk){mk=L.marker([e.lat,e.lng],{icon:L.divIcon({className:'photo-pin',html:'📷',iconSize:[28,28],iconAnchor:[14,14]})}).addTo(map);mk.on('click',()=>showPhotoPopup(e,mk));photoMarkers.set(id,mk)}mk.setOpacity((e.ts||0)<=ts?1:0)});waypoints.forEach((w,id)=>{let mk=wpMarkers.get(id);if(!mk){mk=L.marker([w.lat,w.lng]).addTo(map);wpMarkers.set(id,mk)}mk.setLatLng([w.lat,w.lng]);mk.setOpacity(w.done?.45:1);mk.bindPopup(`<b>${esc(w.title)}</b>${w.note?'<br>'+esc(w.note):''}`)})}
function showPhotoPopup(e,mk){mk.bindPopup(`<b>${esc(e.author||'')}</b><br><small>${fmtTime(e.ts)}</small><br><img src="${e.data}" style="width:220px;max-height:220px;object-fit:cover;border-radius:10px;margin-top:6px">`).openPopup()}
function allTimelineTs(){const a=[];members.forEach(m=>(m.payload?.trail||[]).forEach(p=>a.push(p.ts)));events.forEach(e=>a.push(e.ts));return a.filter(Boolean)}
function updateTimeline(){const a=allTimelineTs(),min=a.length?Math.min(...a):Date.now()-3600000,max=Date.now();els.timeRange.min=String(min);els.timeRange.max=String(max);if(timelineLive)els.timeRange.value=String(max);els.timeLabel.textContent=timelineLive?'LIVE':fmtTime(selectedTs)}
els.timeRange.addEventListener('input',()=>{timelineLive=false;selectedTs=Number(els.timeRange.value);updateTimeline();renderTimelineMap()});els.timelineLive.onclick=()=>{timelineLive=true;selectedTs=Date.now();updateTimeline();renderTimelineMap()};els.liveMap.onclick=els.timelineLive.onclick;
els.fit.onclick=()=>{const pts=[];members.forEach(m=>{if(m.payload?.pos)pts.push([m.payload.pos.lat,m.payload.pos.lng])});waypoints.forEach(w=>pts.push([w.lat,w.lng]));if(pts.length)map.fitBounds(pts,{padding:[35,35],maxZoom:14})};

function renderNow(){const arr=[...members.values()].map(m=>m.payload).filter(Boolean).sort((a,b)=>b.ts-a.ts),fresh=arr[0],target=currentTargetObj();if(fresh){const names=arr.map(x=>x.name||'Путешественник').slice(0,2).join(' + ');els.nowTitle.textContent=names;els.nowSubtitle.textContent=`${motionLabel(fresh.pos)} · GPS ${fmtAge(fresh.ts)}${Number.isFinite(fresh.pos.altitude)?' · '+Math.round(fresh.pos.altitude)+' м':''}`}else{els.nowTitle.textContent='Путешествие начинается';els.nowSubtitle.textContent='Ждём первый GPS-сигнал.'}
 const today=dayKey(Date.now()),tr=fresh?(fresh.trail||[]).filter(p=>dayKey(p.ts||fresh.ts)===today):[],distance=trailDistance(tr),gain=ascent(tr),between=arr.length>1?dist(arr[0].pos,arr[1].pos):NaN;
 els.nowStats.innerHTML=[['Маршрут',km(distance)],['Набор',Number.isFinite(gain)?Math.round(gain)+' м':'—'],['Между нами',Number.isFinite(between)?km(between):'—'],['Фото',String(photoEvents().filter(e=>dayKey(e.ts)===today).length)]].map(([l,v])=>`<div class="stat"><b>${esc(v)}</b><small>${esc(l)}</small></div>`).join('');
 if(target&&!target.done&&fresh){const d=dist(fresh.pos,target),spd=Math.max((fresh.pos.speed||0)*3.6,4),mins=Math.round((d/1000)/spd*60);els.target.textContent=`🎯 ${target.title} · ${km(d)} · ETA ~${mins} мин`}else if(target&&!target.done)els.target.textContent='🎯 '+target.title;else els.target.textContent='🎯 Цель пока не выбрана';
 renderPeople();renderLatest();renderMissionPreview();
}
function renderPeople(){if(!members.size){els.people.innerHTML='<div class="empty">Жду GPS участников…</div>';return}els.people.innerHTML='';[...members.values()].sort((a,b)=>(b.payload?.ts||0)-(a.payload?.ts||0)).forEach(m=>{const p=m.payload,pos=p.pos,spd=Number.isFinite(pos.speed)?pos.speed*3.6:0,alt=Number.isFinite(pos.altitude)?Math.round(pos.altitude)+' м':'LIVE',bat=Number.isFinite(p.battery)?p.battery+'%':'—';const card=document.createElement('div');card.className='traveler card';card.innerHTML=`<div class="traveler-head"><span class="swatch" style="background:${m.color}"></span><h3>${esc(p.name||'Участник')}</h3></div><div class="big">${spd>2?Math.round(spd)+' км/ч':alt}</div><div class="sub">${motionLabel(pos)} · ${fmtAge(p.ts)}<br>${Number.isFinite(pos.accuracy)?'GPS ±'+Math.round(pos.accuracy)+' м':''}</div><div class="status-row"><span class="chip">🔋 ${bat}</span>${Number.isFinite(pos.altitude)?`<span class="chip">⛰ ${Math.round(pos.altitude)} м</span>`:''}<span class="chip">${(p.trail||[]).length} точек</span></div>`;card.onclick=()=>{switchTab('map');setTimeout(()=>map.flyTo([pos.lat,pos.lng],16),100)};els.people.appendChild(card)})}
function renderLatest(){const e=eventArray().find(x=>x.type==='photo'||x.type==='checkin'||x.type==='sos');if(!e){els.latest.innerHTML='<div class="empty">Фотографии и check-in появятся здесь.</div>';return}if(e.type==='photo'){els.latest.innerHTML=`<div class="latest-photo"><img src="${e.data}"><div class="latest-copy"><b>${esc(e.caption||'Фото с маршрута')}</b><p>${esc(e.author||'')}</p><small>${fmtTime(e.ts)}</small></div></div>`}else els.latest.innerHTML=`<div class="latest-copy"><b>${e.type==='sos'?'🚨 SOS':'✅ Мы ок'}</b><p>${esc(e.text||'')}</p><small>${esc(e.author||'')} · ${fmtTime(e.ts)}</small></div>`}
function renderMissionPreview(){const a=[...missions.values()].filter(m=>m.status!=='done').sort((a,b)=>b.ts-a.ts).slice(0,2);if(!a.length){els.missionPreview.innerHTML='<div class="empty">Пока никто ничего не загадал.</div>';return}els.missionPreview.innerHTML='';a.forEach(m=>els.missionPreview.appendChild(missionEl(m,true)))}
function renderPresence(){const now=Date.now();let n=0;presence.forEach(p=>{if(now-(p.ts||0)<55000)n++});els.watchers.textContent=n+' '+(n===1?'смотрит':'смотрят')}

function reactionSummary(id){const r=reactions.get(id)||new Map(),count={};r.forEach(x=>count[x.emoji]=(count[x.emoji]||0)+1);return count}
function renderFeed(){const arr=eventArray().slice(0,80);els.feedCount.textContent=arr.length?'· '+arr.length:'';if(!arr.length){els.feed.innerHTML='<div class="empty">Здесь появятся фотографии, комментарии и события.</div>';return}els.feed.innerHTML='';arr.forEach(e=>{const box=document.createElement('article');box.className='event'+(e.type==='sos'?' sos':'');const icon=e.type==='photo'?'📷':e.type==='checkin'?'✅':e.type==='sos'?'🚨':'💬',body=e.type==='photo'?(e.caption||'Фото с маршрута'):(e.text||'');box.innerHTML=`<div class="event-head"><span>${icon}</span><b>${esc(e.author||'Участник')}</b><small>${fmtTime(e.ts)}</small></div>${body?`<div class="event-text">${esc(body)}</div>`:''}${e.missionId&&missions.get(e.missionId)?`<div class="event-mission">Миссия: ${esc(missions.get(e.missionId).text)}</div>`:''}${e.type==='photo'?`<img class="photo" src="${e.data}" alt="Фото маршрута">`:''}<div class="reacts"></div>`;if(Number.isFinite(e.lat)&&Number.isFinite(e.lng))box.querySelector('.event-head').onclick=()=>{switchTab('map');setTimeout(()=>map.flyTo([e.lat,e.lng],16),100)};const rs=box.querySelector('.reacts'),sum=reactionSummary(e.id);['❤️','😂','🔥','😱','👏'].forEach(em=>{const b=document.createElement('button');b.className='react';b.textContent=em+(sum[em]?' '+sum[em]:'');b.onclick=()=>publish(`${V2}/reaction/${e.id}/${viewerId}`,{target:e.id,viewerId,emoji:em,ts:Date.now(),name:myName||'Зритель'});rs.appendChild(b)});els.feed.appendChild(box)})}

function renderWaypoints(){const arr=[...waypoints.values()].sort((a,b)=>(a.order||a.ts)-(b.order||b.ts));if(!arr.length){els.wps.innerHTML='<div class="empty">Маршрут пока пуст. Добавь первую точку.</div>';return}els.wps.innerHTML='';const pos=freshestMember()?.pos;arr.forEach(w=>{const d=pos?dist(pos,w):NaN,el=document.createElement('div');el.className='wp';el.innerHTML=`<div class="wp-top"><div><b>${currentWaypointId===w.id?'🎯 ':''}${w.done?'✓ ':''}${esc(w.title)}</b><small>${Number.isFinite(d)?km(d):''}${w.note?' · '+esc(w.note):''}</small></div></div><div class="wp-actions"><button class="mini" data-act="target">🎯 Цель</button><button class="mini" data-act="done">${w.done?'↩ Вернуть':'✓ Пройдено'}</button></div>`;el.querySelector('[data-act=target]').onclick=()=>{currentWaypointId=w.id;publish(`${V2}/state/currentWaypoint`,{id:w.id,ts:Date.now(),by:myName||'viewer'});renderAll()};el.querySelector('[data-act=done]').onclick=()=>{w.done=!w.done;w.updated=Date.now();publish(`${V2}/waypoint/${w.id}`,w);renderAll()};els.wps.appendChild(el)})}
function missionEl(m,compact=false){const el=document.createElement('div');el.className='mission'+(m.status==='done'?' done':'');const status=m.status==='done'?'выполнено':m.status==='accepted'?'принято':'открыто';el.innerHTML=`<div class="mission-top"><div><b>${esc(m.text)}</b><small>${esc(m.author||'Зритель')} · ${status}</small></div><span>${m.status==='done'?'✅':m.status==='accepted'?'🟡':'🎯'}</span></div><div class="mission-actions"></div>`;const actions=el.querySelector('.mission-actions');if(role==='travel'&&m.status==='open'){const b=document.createElement('button');b.className='mini primary-mini';b.textContent='Принять';b.onclick=()=>{m.status='accepted';m.acceptedBy=myName;m.updated=Date.now();publish(`${V2}/mission/${m.id}`,m)};actions.appendChild(b)}if(role==='travel'&&m.status==='accepted'){const b=document.createElement('button');b.className='mini primary-mini';b.textContent='📷 Выполнить фото';b.onclick=()=>{pendingMissionId=m.id;els.photoInput.click()};actions.appendChild(b)}if(!compact&&m.status!=='done'&&m.authorId===viewerId){const b=document.createElement('button');b.className='mini';b.textContent='Закрыть';b.onclick=()=>{m.status='done';m.updated=Date.now();publish(`${V2}/mission/${m.id}`,m)};actions.appendChild(b)}return el}
function renderMissions(){const arr=[...missions.values()].sort((a,b)=>{const rank={accepted:0,open:1,done:2};return (rank[a.status]??1)-(rank[b.status]??1)||b.ts-a.ts});if(!arr.length){els.missions.innerHTML='<div class="empty">Миссий ещё нет.</div>';return}els.missions.innerHTML='';arr.forEach(m=>els.missions.appendChild(missionEl(m,false)))}

function getDayData(){const days=new Map();const ensure=k=>{if(!days.has(k))days.set(k,{key:k,dist:0,gain:0,photos:[],checkins:0,comments:0,points:0});return days.get(k)};members.forEach(m=>{const by={};(m.payload?.trail||[]).forEach(p=>{if(!p.ts)return;const k=dayKey(p.ts);(by[k]||(by[k]=[])).push(p)});Object.entries(by).forEach(([k,tr])=>{const d=ensure(k);d.dist+=trailDistance(tr);d.gain+=ascent(tr);d.points+=tr.length})});events.forEach(e=>{if(!e.ts)return;const d=ensure(dayKey(e.ts));if(e.type==='photo')d.photos.push(e);if(e.type==='checkin')d.checkins++});comments.forEach(c=>{if(c.ts)ensure(dayKey(c.ts)).comments++});return [...days.values()].sort((a,b)=>b.key.localeCompare(a.key))}
function renderDays(){const arr=getDayData();if(!arr.length){els.days.innerHTML='<div class="empty">Сводка появится после первых GPS-точек.</div>';return}els.days.innerHTML='';arr.forEach((d,i)=>{const el=document.createElement('div');el.className='day card';el.innerHTML=`<div class="date">DAY ${arr.length-i}</div><h3>${esc(prettyDay(d.key))}</h3><div class="day-stats"><div class="day-stat"><b>${km(d.dist)}</b><small>маршрут</small></div><div class="day-stat"><b>${Math.round(d.gain)} м</b><small>набор</small></div><div class="day-stat"><b>${d.photos.length}</b><small>фото</small></div><div class="day-stat"><b>${d.checkins}</b><small>check-in</small></div></div>${d.photos.length?`<div class="thumbs">${d.photos.slice(0,4).map(p=>`<img src="${p.data}" alt="Фото дня">`).join('')}</div>`:''}`;els.days.appendChild(el)})}

async function maybeWeather(){const p=freshestMember()?.pos;if(!p)return;const key=Math.round(p.lat*100)/100+','+Math.round(p.lng*100)/100;if(weatherCache.key===key&&Date.now()-weatherCache.ts<300000){renderWeather(weatherCache.data);return}try{const r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${encodeURIComponent(p.lat)}&longitude=${encodeURIComponent(p.lng)}&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m&timezone=auto`);if(!r.ok)return;const j=await r.json();weatherCache={key,ts:Date.now(),data:j.current};renderWeather(j.current)}catch(e){}}
function weatherIcon(code){if(code===0)return'☀️';if(code<=3)return'⛅';if(code<=48)return'🌫️';if(code<=67)return'🌧️';if(code<=77)return'🌨️';if(code<=82)return'🌦️';if(code<=99)return'⛈️';return'🌡️'}
function renderWeather(w){if(!w)return;els.weather.textContent=`${weatherIcon(w.weather_code)} ${Math.round(w.temperature_2m)}° · ${Math.round(w.wind_speed_10m||0)} км/ч`}

function renderAll(){renderTimelineMap();updateTimeline();renderNow();renderFeed();renderWaypoints();renderMissions();renderPresence();if(currentTab==='days')renderDays();els.quick.style.display=role==='travel'?'grid':'none'}
function onV2(topic,p){const rel=topic.slice((V2+'/').length),parts=rel.split('/');if(parts[0]==='event'){events.set(parts[1],p)}else if(parts[0]==='comment'){comments.set(parts[1],p)}else if(parts[0]==='waypoint'){waypoints.set(parts[1],p)}else if(parts[0]==='reaction'){if(!reactions.has(parts[1]))reactions.set(parts[1],new Map());reactions.get(parts[1]).set(parts[2],p)}else if(parts[0]==='presence'){presence.set(parts[1],p)}else if(parts[0]==='mission'){missions.set(parts[1],p)}else if(parts[0]==='state'&&parts[1]==='currentWaypoint'){currentWaypointId=p.id}renderAll()}

const client=mqtt.connect(BROKER,{clientId:'tat_final_'+Math.random().toString(16).slice(2),clean:true,reconnectPeriod:2500,connectTimeout:10000,keepalive:30});
client.on('connect',()=>{setBroker(true,'Онлайн');client.subscribe(`${V1}/member/+`);client.subscribe(`${V2}/#`);heartbeat()});client.on('reconnect',()=>setBroker(null,'Переподключаюсь…'));client.on('offline',()=>setBroker(false,'Нет связи'));client.on('error',()=>setBroker(false,'Ошибка канала'));client.on('message',(topic,b)=>{try{const p=JSON.parse(b.toString());if(topic.startsWith(V1+'/member/'))upsertMember(p);else if(topic.startsWith(V2+'/'))onV2(topic,p)}catch(e){}});
function heartbeat(){if(!client.connected)return;publish(`${V2}/presence/${viewerId}`,{id:viewerId,name:myName||'Зритель',role,ts:Date.now()},true)}setInterval(heartbeat,18000);setInterval(()=>{renderPresence();renderNow();updateTimeline()},5000);setInterval(maybeWeather,300000);

function setIdentity(name,newRole){myName=name.trim()||'Зритель';role=newRole;localStorage.setItem(`tat-name-${room}`,myName);localStorage.setItem(`tat-role-${room}`,role);els.join.classList.remove('show');heartbeat();renderAll();toast(role==='travel'?'Режим путешественника':'Режим зрителя')}
els.joinTravel.onclick=()=>setIdentity(els.name.value,'travel');els.joinWatch.onclick=()=>setIdentity(els.name.value,'watch');

function startTracking(){if(nativeMode){toast('Фоновый GPS уже ведёт приложение');return}if(role!=='travel'){toast('Переключись в режим путешественника');return}if(!navigator.geolocation){toast('GPS не поддерживается');return}if(tracking){navigator.geolocation.clearWatch(watchId);watchId=null;tracking=false;els.track.classList.remove('active');toast('GPS браузера остановлен');return}tracking=true;els.track.classList.add('active');watchId=navigator.geolocation.watchPosition(onBrowserPos,e=>{toast(e.code===1?'GPS запрещён':'GPS недоступен')},{enableHighAccuracy:true,maximumAge:7000,timeout:20000});toast('GPS браузера включён')}
function onBrowserPos(g){const now=Date.now(),p={lat:g.coords.latitude,lng:g.coords.longitude,accuracy:g.coords.accuracy,altitude:g.coords.altitude,speed:g.coords.speed,heading:g.coords.heading,ts:g.timestamp||now};if(lastPublished&&dist(lastPublished,p)<7&&now-lastPublishAt<9000)return;lastPublished=p;lastPublishAt=now;const prev=myTrail.at(-1);if(!prev||dist(prev,p)>=7||now-prev.ts>15000)myTrail.push({lat:p.lat,lng:p.lng,altitude:p.altitude,ts:now});if(myTrail.length>500)myTrail=myTrail.slice(-500);localStorage.setItem(`tat-trail-${room}-${webDeviceId}`,JSON.stringify(myTrail));const payload={v:3,id:webDeviceId,name:myName,ts:now,pos:p,trail:myTrail.slice(-300)};publish(`${V1}/member/${webDeviceId}`,payload,true);upsertMember(payload)}
els.track.onclick=startTracking;
async function getCurrentPos(){const own=myMember()?.pos;if(own)return own;if(!navigator.geolocation)throw new Error('no gps');return new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(g=>res({lat:g.coords.latitude,lng:g.coords.longitude,accuracy:g.coords.accuracy,altitude:g.coords.altitude}),rej,{enableHighAccuracy:true,timeout:12000,maximumAge:15000}))}

async function compressImage(file){const data=await new Promise((r,j)=>{const fr=new FileReader();fr.onload=()=>r(fr.result);fr.onerror=j;fr.readAsDataURL(file)}),img=await new Promise((r,j)=>{const i=new Image();i.onload=()=>r(i);i.onerror=j;i.src=data});let max=760,quality=.66,best='';for(let attempt=0;attempt<6;attempt++){const s=Math.min(1,max/Math.max(img.width,img.height)),w=Math.max(1,Math.round(img.width*s)),h=Math.max(1,Math.round(img.height*s)),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);best=c.toDataURL('image/jpeg',quality);if(best.length<125000)break;max=Math.round(max*.84);quality=Math.max(.42,quality-.06)}return best}
async function addPhoto(file){if(!file)return;try{toast('Сжимаю фото…');const [data,pos]=await Promise.all([compressImage(file),getCurrentPos()]);const caption=prompt('Подпись к фото?','')||'',id=rid(),e={id,type:'photo',author:myName||'Путешественник',authorId:viewerId,ts:Date.now(),lat:pos.lat,lng:pos.lng,caption,data,missionId:pendingMissionId||null};if(publish(`${V2}/event/${id}`,e,true)){events.set(id,e);if(pendingMissionId&&missions.has(pendingMissionId)){const m=missions.get(pendingMissionId);m.status='done';m.completedBy=myName;m.proofEvent=id;m.updated=Date.now();publish(`${V2}/mission/${m.id}`,m,true);pendingMissionId=null}renderAll();toast('Фото в журнале')}}catch(e){toast('Не удалось добавить фото')}}
els.photo.onclick=()=>els.photoInput.click();els.feedPhoto.onclick=()=>els.photoInput.click();els.photoInput.onchange=async()=>{const f=els.photoInput.files?.[0];els.photoInput.value='';await addPhoto(f)};
function addEvent(type,text){const pos=currentPos(),id=rid(),e={id,type,author:myName||'Путешественник',authorId:viewerId,ts:Date.now(),text,lat:pos?.lat??null,lng:pos?.lng??null};publish(`${V2}/event/${id}`,e,true);events.set(id,e);renderAll()}
els.checkin.onclick=()=>addEvent('checkin','Всё хорошо, продолжаем маршрут.');els.sos.onclick=()=>{if(confirm('Отправить SOS-событие всем, кто смотрит поездку? Это не заменяет 112.'))addEvent('sos','Нужна помощь. Последняя доступная позиция прикреплена к событию.')};

els.commentBtn.onclick=()=>{const text=els.comment.value.trim();if(!text)return;const id=rid(),c={id,type:'comment',author:myName||'Зритель',authorId:viewerId,ts:Date.now(),text};publish(`${V2}/comment/${id}`,c,true);els.comment.value='';comments.set(id,c);renderFeed()};els.comment.addEventListener('keydown',e=>{if(e.key==='Enter')els.commentBtn.click()});

els.waypointBtn.onclick=()=>{pendingWaypoint=true;els.wpHint.classList.remove('hidden');switchTab('map');toast('Ткни по карте')};map.on('click',e=>{if(!pendingWaypoint)return;pendingWaypoint=false;els.wpHint.classList.add('hidden');const title=prompt('Название точки?','Следующая точка');if(!title)return;const note=prompt('Заметка?','')||'',id=rid(),w={id,title,note,lat:e.latlng.lat,lng:e.latlng.lng,ts:Date.now(),order:Date.now(),done:false,author:myName||'Участник'};waypoints.set(id,w);publish(`${V2}/waypoint/${id}`,w,true);if(!currentWaypointId){currentWaypointId=id;publish(`${V2}/state/currentWaypoint`,{id,ts:Date.now(),by:myName||'viewer'},true)}renderAll();switchTab('plan')});

els.missionBtn.onclick=()=>{const text=els.missionInput.value.trim();if(!text)return;const id=rid(),m={id,text,author:myName||'Зритель',authorId:viewerId,ts:Date.now(),status:'open'};missions.set(id,m);publish(`${V2}/mission/${id}`,m,true);els.missionInput.value='';renderMissions();renderMissionPreview();toast('Миссия отправлена')};els.missionInput.addEventListener('keydown',e=>{if(e.key==='Enter')els.missionBtn.click()});

function shareUrl(){const u=new URL(location.href);u.searchParams.set('room',room);u.searchParams.delete('name');u.searchParams.delete('role');u.searchParams.delete('native');return u.toString()}
els.share.onclick=async()=>{const url=shareUrl();try{if(navigator.share)await navigator.share({title:'Trip-a-Trip · Romania Live',text:'Смотри наше путешествие вживую',url});else{await navigator.clipboard.writeText(url);toast('Ссылка скопирована')}}catch(e){}};

async function buildPostcard(){const p=freshestMember(),target=currentTargetObj(),today=getDayData().find(d=>d.key===dayKey(Date.now())),photos=photoEvents(),latest=photos[0];const c=document.createElement('canvas');c.width=1080;c.height=1350;const x=c.getContext('2d');x.fillStyle='#08111f';x.fillRect(0,0,c.width,c.height);if(latest?.data){try{const img=await new Promise((r,j)=>{const i=new Image();i.onload=()=>r(i);i.onerror=j;i.src=latest.data});const scale=Math.max(c.width/img.width,700/img.height),w=img.width*scale,h=img.height*scale;x.globalAlpha=.82;x.drawImage(img,(c.width-w)/2,0,w,h);x.globalAlpha=1;const g=x.createLinearGradient(0,0,0,780);g.addColorStop(0,'rgba(8,17,31,.05)');g.addColorStop(1,'#08111f');x.fillStyle=g;x.fillRect(0,0,c.width,800)}catch(e){}}
 x.fillStyle='#7dd3fc';x.font='700 30px system-ui';x.fillText('TRIP-A-TRIP · ROMANIA LIVE',70,780);x.fillStyle='#ffffff';x.font='800 64px system-ui';wrapText(x,p?.name||'Romania trip',70,860,940,76,2);x.fillStyle='#9fb1c5';x.font='400 34px system-ui';x.fillText(new Date().toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'}),70,1030);const stats=[['МАРШРУТ',today?km(today.dist):'—'],['ВЫСОТА',Number.isFinite(p?.pos?.altitude)?Math.round(p.pos.altitude)+' м':'—'],['ФОТО',String(today?.photos.length||0)],['ЦЕЛЬ',target&&!target.done?target.title:'свободный маршрут']];stats.forEach((s,i)=>{const col=i%2,row=Math.floor(i/2),sx=70+col*490,sy=1110+row*110;x.fillStyle='#7f94aa';x.font='700 22px system-ui';x.fillText(s[0],sx,sy);x.fillStyle='#fff';x.font='700 30px system-ui';wrapText(x,s[1],sx,sy+38,430,34,1)});postcardBlob=await new Promise(r=>c.toBlob(r,'image/jpeg',.9));els.postcardPreview.src=URL.createObjectURL(postcardBlob);els.postcardModal.classList.add('show')}
function wrapText(ctx,text,x,y,maxWidth,lineHeight,maxLines=99){const words=String(text).split(' ');let line='',lines=0;for(const w of words){const test=line?line+' '+w:w;if(ctx.measureText(test).width>maxWidth&&line){ctx.fillText(line,x,y+lines*lineHeight);lines++;line=w;if(lines>=maxLines)return}else line=test}if(line&&lines<maxLines)ctx.fillText(line,x,y+lines*lineHeight)}
els.postcardBtn.onclick=buildPostcard;els.daysPostcard.onclick=buildPostcard;els.postcardClose.onclick=()=>els.postcardModal.classList.remove('show');els.postcardModal.addEventListener('click',e=>{if(e.target===els.postcardModal)els.postcardModal.classList.remove('show')});els.postcardShare.onclick=async()=>{if(!postcardBlob)return;const file=new File([postcardBlob],'trip-a-trip-romania.jpg',{type:'image/jpeg'});try{if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:'Trip-a-Trip · Romania'});else await navigator.share?.({title:'Trip-a-Trip · Romania',url:shareUrl()})}catch(e){}};els.postcardSave.onclick=()=>{if(!postcardBlob)return;const a=document.createElement('a');a.href=URL.createObjectURL(postcardBlob);a.download='trip-a-trip-romania.jpg';a.click()};

renderAll();
})();
