(()=>{
const qs=new URLSearchParams(location.search);let room=qs.get('room');
if(!room){room=(crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random().toString(36)).replace(/-/g,'');qs.set('room',room);history.replaceState(null,'',location.pathname+'?'+qs)}
const v1=`trip-a-trip/v1/${room}`,v2=`trip-a-trip/v2/${room}`,broker='wss://broker.emqx.io:8084/mqtt';
const rid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const viewerId=localStorage.getItem('tat-viewer-id')||rid();localStorage.setItem('tat-viewer-id',viewerId);
const deviceId=localStorage.getItem(`tat-device-${room}`)||rid();localStorage.setItem(`tat-device-${room}`,deviceId);
let myName=localStorage.getItem(`tat-name-${room}`)||'',role=localStorage.getItem(`tat-role-${room}`)||'watch';
let tracking=false,watchId=null,lastPublished=null,lastPublishAt=0,pendingWaypoint=false,currentWaypointId=null,selectedTs=Date.now(),timelineLive=true;
let myTrail=JSON.parse(localStorage.getItem(`tat-trail-${room}-${deviceId}`)||'[]');if(!Array.isArray(myTrail))myTrail=[];
const members=new Map(),events=new Map(),waypoints=new Map(),reactions=new Map(),comments=new Map(),presence=new Map(),photoMarkers=new Map(),wpMarkers=new Map();
const $=id=>document.getElementById(id),els={dot:$('brokerDot'),broker:$('brokerText'),room:$('roomLabel'),people:$('people'),track:$('trackBtn'),share:$('shareBtn'),fit:$('fitBtn'),photo:$('photoBtn'),photoInput:$('photoInput'),waypoint:$('waypointBtn'),checkin:$('checkinBtn'),range:$('timeRange'),time:$('timeLabel'),live:$('liveBtn'),wps:$('waypoints'),target:$('currentTarget'),feed:$('feed'),feedCount:$('feedCount'),comment:$('commentInput'),commentBtn:$('commentBtn'),watchers:$('watchers'),modal:$('joinModal'),name:$('nameInput'),joinShare:$('joinShare'),joinWatch:$('joinWatch'),toast:$('toast')};
els.room.textContent='комната '+room.slice(0,8);
const map=L.map('map',{zoomControl:false}).setView([45.45,25.5],8);L.control.zoom({position:'topright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);
const palette=['#38bdf8','#fb7185','#a78bfa','#4ade80','#facc15','#fb923c','#2dd4bf','#e879f9'];
function colorFor(id){let h=0;for(const c of id)h=((h<<5)-h)+c.charCodeAt(0);return palette[Math.abs(h)%palette.length]}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmtAge(ts){const s=Math.max(0,Math.floor((Date.now()-ts)/1000));return s<10?'сейчас':s<60?s+'с назад':s<3600?Math.floor(s/60)+'м назад':Math.floor(s/3600)+'ч назад'}
function fmtTime(ts){return new Date(ts).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}
function km(m){return m<1000?Math.round(m)+' м':(m/1000).toFixed(m<10000?1:0)+' км'}
function dist(a,b){if(!a||!b)return Infinity;const R=6371e3,p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dp=(b.lat-a.lat)*Math.PI/180,dl=(b.lng-a.lng)*Math.PI/180,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function toast(t){els.toast.textContent=t;els.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.remove('show'),1800)}
function setBroker(ok,text){els.dot.className='dot '+(ok===true?'on':ok===false?'err':'');els.broker.textContent=text}
function publish(topic,obj,retain=true){if(!client.connected){toast('Нет связи');return}client.publish(topic,JSON.stringify(obj),{qos:0,retain})}
function memberPosAt(p,ts){const tr=(p.trail||[]).filter(x=>x.ts<=ts);if(tr.length)return tr[tr.length-1];return p.ts<=ts?p.pos:null}
function upsertMember(p){if(!p?.id||!p?.pos)return;let m=members.get(p.id),c=colorFor(p.id);if(!m){m={color:c,line:L.polyline([],{color:c,weight:4,opacity:.9}).addTo(map),dot:L.circleMarker([p.pos.lat,p.pos.lng],{radius:9,color:'#fff',weight:3,fillColor:c,fillOpacity:1}).addTo(map)};m.dot.bindTooltip(p.name||'Участник',{permanent:true,direction:'top',offset:[0,-10],className:'member-tip'});members.set(p.id,m)}m.payload=p;renderTimelineMap();renderPeople()}
function renderPeople(){
 if(!members.size){els.people.innerHTML='<div class="empty">Жду GPS…</div>';return}
 els.people.innerHTML='';[...members.values()].sort((a,b)=>(b.payload.ts||0)-(a.payload.ts||0)).forEach(m=>{const p=m.payload,pos=p.pos,spd=Number.isFinite(pos.speed)?pos.speed*3.6:null,bat=Number.isFinite(p.battery)?` · 🔋${p.battery}%`:'',alt=Number.isFinite(pos.altitude)?`${Math.round(pos.altitude)} м`:'';const el=document.createElement('div');el.className='person';el.innerHTML=`<div class="personTop"><span class="swatch" style="background:${m.color}"></span><strong>${esc(p.name||'Участник')}</strong></div><div class="big">${spd&&spd>2?Math.round(spd)+' км/ч':alt||'LIVE'}</div><div class="meta">${fmtAge(p.ts)}${bat}<br>${Number.isFinite(pos.accuracy)?'GPS ±'+Math.round(pos.accuracy)+' м':''}</div>`;el.onclick=()=>map.flyTo([pos.lat,pos.lng],16);els.people.appendChild(el)})
}
function renderTimelineMap(){
 const ts=timelineLive?Date.now():selectedTs;
 members.forEach(m=>{const p=m.payload,pts=(p.trail||[]).filter(x=>x.ts<=ts).map(x=>[x.lat,x.lng]);m.line.setLatLngs(pts);const at=memberPosAt(p,ts);if(at){m.dot.setLatLng([at.lat,at.lng]);m.dot.setStyle({opacity:1,fillOpacity:1})}else m.dot.setStyle({opacity:0,fillOpacity:0})});
 events.forEach((e,id)=>{if(e.type!=='photo')return;let mk=photoMarkers.get(id);if(!mk){mk=L.marker([e.lat,e.lng],{icon:L.divIcon({className:'photo-pin',html:'📷',iconSize:[26,26],iconAnchor:[13,13]})}).addTo(map);mk.on('click',()=>showPhotoPopup(e,mk));photoMarkers.set(id,mk)}mk.setOpacity(e.ts<=ts?1:0)});
}
function showPhotoPopup(e,mk){mk.bindPopup(`<b>${esc(e.author)}</b><br><small>${fmtTime(e.ts)}</small><br><img src="${e.data}" style="width:220px;max-height:220px;object-fit:cover;border-radius:10px;margin-top:6px">`).openPopup()}
function renderWaypoints(){
 const arr=[...waypoints.values()].sort((a,b)=>(a.order||a.ts)-(b.order||b.ts));els.wps.innerHTML='';if(!arr.length){els.wps.innerHTML='<div class="empty">Нажми «📍 Точка», потом ткни по карте.</div>';els.target.textContent='нет текущей цели';return}
 let firstMember=[...members.values()][0]?.payload?.pos;let current=waypoints.get(currentWaypointId);els.target.textContent=current&&!current.done?'🎯 '+current.title:'нет текущей цели';
 arr.forEach(w=>{let mk=wpMarkers.get(w.id);if(!mk){mk=L.marker([w.lat,w.lng]).addTo(map).bindPopup(`<b>${esc(w.title)}</b>${w.note?'<br>'+esc(w.note):''}`);wpMarkers.set(w.id,mk)}mk.setOpacity(w.done?.45:1);const d=firstMember?dist(firstMember,w):null;const el=document.createElement('div');el.className='wp'+(w.done?' done':'');el.innerHTML=`<div><strong>${currentWaypointId===w.id?'🎯 ':''}${esc(w.title)}</strong><small>${d?km(d):''}${w.note?' · '+esc(w.note):''}</small></div><div class="wpBtns"><button class="mini" data-a="target">🎯</button><button class="mini" data-a="done">${w.done?'↩':'✓'}</button></div>`;el.querySelector('[data-a=target]').onclick=()=>{currentWaypointId=w.id;publish(v2+'/state/currentWaypoint',{id:w.id,ts:Date.now(),by:myName||'viewer'});renderWaypoints()};el.querySelector('[data-a=done]').onclick=()=>{w.done=!w.done;w.updated=Date.now();publish(v2+'/waypoint/'+w.id,w);renderWaypoints()};el.onclick=e=>{if(e.target.tagName!=='BUTTON')map.flyTo([w.lat,w.lng],15)};els.wps.appendChild(el)})
}
function renderPresence(){const now=Date.now();let n=0;presence.forEach(p=>{if(now-p.ts<55000)n++});els.watchers.textContent=n+' '+(n===1?'смотрит':'смотрят')}
function allTimelineTs(){const a=[];members.forEach(m=>(m.payload.trail||[]).forEach(p=>a.push(p.ts)));events.forEach(e=>a.push(e.ts));return a.filter(Boolean)}
function updateTimelineBounds(){const a=allTimelineTs();const min=a.length?Math.min(...a):Date.now()-3600000,max=Date.now();els.range.min=String(min);els.range.max=String(max);if(timelineLive)els.range.value=String(max);els.time.textContent=timelineLive?'LIVE':fmtTime(selectedTs)}
function reactionSummary(id){const r=reactions.get(id)||new Map(),count={};r.forEach(x=>count[x.emoji]=(count[x.emoji]||0)+1);return count}
function renderFeed(){
 const arr=[...events.values(),...comments.values()].sort((a,b)=>b.ts-a.ts).slice(0,60);els.feedCount.textContent=arr.length;els.feed.innerHTML='';if(!arr.length){els.feed.innerHTML='<div class="empty">Здесь появятся фото, check-in и комментарии.</div>';return}
 arr.forEach(e=>{const box=document.createElement('div');box.className='event'+(e.type==='sos'?' sos':'');let icon=e.type==='photo'?'📷':e.type==='checkin'?'✅':e.type==='sos'?'🚨':'💬';let body=e.type==='photo'?(e.caption||'Фото с маршрута'):e.text||'';box.innerHTML=`<div class="eventHead"><span>${icon}</span><b>${esc(e.author||'Участник')}</b><small>${fmtTime(e.ts)}</small></div>${body?`<div class="eventText">${esc(body)}</div>`:''}${e.type==='photo'?`<img class="photo" src="${e.data}">`:''}<div class="reacts"></div>`;if(e.lat&&e.lng)box.querySelector('.eventHead').onclick=()=>map.flyTo([e.lat,e.lng],16);const rs=box.querySelector('.reacts'),sum=reactionSummary(e.id);['❤️','😂','🔥','😱','👏'].forEach(em=>{const b=document.createElement('button');b.className='react';b.textContent=em+(sum[em]?' '+sum[em]:'');b.onclick=()=>publish(v2+`/reaction/${e.id}/${viewerId}`,{target:e.id,viewerId,emoji:em,ts:Date.now(),name:myName||'Зритель'});rs.appendChild(b)});els.feed.appendChild(box)})
}
function onV2(topic,p){const rel=topic.slice((v2+'/').length),parts=rel.split('/');if(parts[0]==='event'){events.set(parts[1],p);renderFeed();renderTimelineMap();updateTimelineBounds()}else if(parts[0]==='comment'){comments.set(parts[1],p);renderFeed()}else if(parts[0]==='waypoint'){waypoints.set(parts[1],p);renderWaypoints()}else if(parts[0]==='reaction'){if(!reactions.has(parts[1]))reactions.set(parts[1],new Map());reactions.get(parts[1]).set(parts[2],p);renderFeed()}else if(parts[0]==='presence'){presence.set(parts[1],p);renderPresence()}else if(parts[0]==='state'&&parts[1]==='currentWaypoint'){currentWaypointId=p.id;renderWaypoints()}}
const client=mqtt.connect(broker,{clientId:'tat_web_'+Math.random().toString(16).slice(2),clean:true,reconnectPeriod:2500,connectTimeout:10000,keepalive:30});
client.on('connect',()=>{setBroker(true,'Онлайн · live-канал подключён');client.subscribe(v1+'/member/+');client.subscribe(v2+'/#');heartbeat()});client.on('reconnect',()=>setBroker(null,'Переподключаюсь…'));client.on('offline',()=>setBroker(false,'Нет связи'));client.on('error',()=>setBroker(false,'Ошибка live-канала'));client.on('message',(topic,b)=>{try{const p=JSON.parse(b.toString());if(topic.startsWith(v1+'/member/'))upsertMember(p);else if(topic.startsWith(v2+'/'))onV2(topic,p)}catch(e){}});
function heartbeat(){if(!client.connected)return;publish(v2+'/presence/'+viewerId,{id:viewerId,name:myName||'Зритель',role,ts:Date.now()},true)}setInterval(heartbeat,18000);setInterval(()=>{renderPresence();renderPeople();updateTimelineBounds()},5000);
function startTracking(){if(!myName){showJoin();return}if(!navigator.geolocation){toast('GPS не поддерживается');return}tracking=true;role='travel';localStorage.setItem(`tat-role-${room}`,role);els.track.textContent='Стоп GPS';els.track.classList.add('active');watchId=navigator.geolocation.watchPosition(onPos,e=>{toast(e.code===1?'GPS запрещён':'GPS недоступен');stopTracking()},{enableHighAccuracy:true,maximumAge:7000,timeout:20000})}
function stopTracking(){if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=null;tracking=false;els.track.textContent='Мой GPS';els.track.classList.remove('active')}
function onPos(g){const p={lat:g.coords.latitude,lng:g.coords.longitude,accuracy:g.coords.accuracy,altitude:g.coords.altitude,speed:g.coords.speed,heading:g.coords.heading,ts:g.timestamp||Date.now()},now=Date.now();if(lastPublished&&dist(lastPublished,p)<7&&now-lastPublishAt<9000)return;lastPublished=p;lastPublishAt=now;const prev=myTrail.at(-1);if(!prev||dist(prev,p)>=7||now-prev.ts>15000)myTrail.push({lat:p.lat,lng:p.lng,ts:now});if(myTrail.length>500)myTrail=myTrail.slice(-500);localStorage.setItem(`tat-trail-${room}-${deviceId}`,JSON.stringify(myTrail));const payload={v:2,id:deviceId,name:myName,ts:now,pos:p,trail:myTrail.slice(-260)};publish(v1+'/member/'+deviceId,payload,true);upsertMember(payload)}
async function getCurrentPos(){const own=members.get(deviceId)?.payload?.pos;if(own)return own;return new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(g=>res({lat:g.coords.latitude,lng:g.coords.longitude}),rej,{enableHighAccuracy:true,timeout:12000,maximumAge:15000}))}
async function compressImage(file){const data=await new Promise((r,j)=>{const fr=new FileReader();fr.onload=()=>r(fr.result);fr.onerror=j;fr.readAsDataURL(file)});const img=await new Promise((r,j)=>{const i=new Image();i.onload=()=>r(i);i.onerror=j;i.src=data});let max=720,s=Math.min(1,max/Math.max(img.width,img.height)),w=Math.round(img.width*s),h=Math.round(img.height*s),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);let q=.56,out=c.toDataURL('image/jpeg',q);while(out.length>170000&&q>.28){q-=.07;out=c.toDataURL('image/jpeg',q)}if(out.length>200000)throw new Error('Фото слишком тяжёлое');return out}
async function addPhoto(file){try{toast('Сжимаю фото…');const [data,pos]=await Promise.all([compressImage(file),getCurrentPos()]);const id=rid(),caption=prompt('Подпись к фото (можно пусто):','')||'';publish(v2+'/event/'+id,{id,type:'photo',author:myName||'Путешественник',ts:Date.now(),lat:pos.lat,lng:pos.lng,caption,data},true);toast('Фото на карте ✓')}catch(e){toast(e.message||'Не удалось добавить фото')}}
map.on('click',e=>{if(!pendingWaypoint)return;pendingWaypoint=false;els.waypoint.classList.remove('active');const title=prompt('Название точки:','Следующая остановка');if(!title)return;const note=prompt('Заметка (можно пусто):','')||'',id=rid(),w={id,title,note,lat:e.latlng.lat,lng:e.latlng.lng,ts:Date.now(),done:false,author:myName||'Участник'};publish(v2+'/waypoint/'+id,w,true);toast('Точка добавлена')});
function checkin(){getCurrentPos().then(pos=>{const id=rid();publish(v2+'/event/'+id,{id,type:'checkin',author:myName||'Путешественник',text:'Мы ок 👌',ts:Date.now(),lat:pos.lat,lng:pos.lng},true);toast('Check-in отправлен')}).catch(()=>toast('Нужна геолокация'))}
function sendComment(){const t=els.comment.value.trim();if(!t)return;const id=rid();publish(v2+'/comment/'+id,{id,type:'comment',author:myName||'Зритель',text:t,ts:Date.now()},true);els.comment.value=''}
async function shareRoom(){const url=`https://raw.githack.com/aisarus/trip-a-trip/main/live.html?room=${encodeURIComponent(room)}`,data={title:'Trip-a-Trip · Romania Live',text:'Смотри наш маршрут в Румынии',url};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(url);toast('Ссылка скопирована')}}catch(e){}}
function fitAll(){const pts=[];members.forEach(m=>m.payload?.pos&&pts.push([m.payload.pos.lat,m.payload.pos.lng]));waypoints.forEach(w=>pts.push([w.lat,w.lng]));if(!pts.length)return;if(pts.length===1)map.flyTo(pts[0],15);else map.fitBounds(pts,{padding:[40,40],maxZoom:14})}
function showJoin(){els.name.value=myName;els.modal.classList.add('show');setTimeout(()=>els.name.focus(),50)}function join(r){const n=els.name.value.trim();if(!n){els.name.focus();return}myName=n;role=r;localStorage.setItem(`tat-name-${room}`,n);localStorage.setItem(`tat-role-${room}`,r);els.modal.classList.remove('show');heartbeat();if(r==='travel')startTracking()}
els.track.onclick=()=>tracking?stopTracking():startTracking();els.share.onclick=shareRoom;els.fit.onclick=fitAll;els.photo.onclick=()=>els.photoInput.click();els.photoInput.onchange=e=>{if(e.target.files[0])addPhoto(e.target.files[0]);e.target.value=''};els.waypoint.onclick=()=>{pendingWaypoint=!pendingWaypoint;els.waypoint.classList.toggle('active',pendingWaypoint);toast(pendingWaypoint?'Ткни по карте, где будет точка':'Отменено')};els.checkin.onclick=checkin;els.commentBtn.onclick=sendComment;els.comment.onkeydown=e=>{if(e.key==='Enter')sendComment()};els.joinShare.onclick=()=>join('travel');els.joinWatch.onclick=()=>join('watch');els.range.oninput=()=>{selectedTs=Number(els.range.value);timelineLive=selectedTs>=Number(els.range.max)-4000;els.time.textContent=timelineLive?'LIVE':fmtTime(selectedTs);renderTimelineMap()};els.live.onclick=()=>{timelineLive=true;selectedTs=Date.now();updateTimelineBounds();renderTimelineMap()};if(!myName)setTimeout(showJoin,350);else heartbeat();updateTimelineBounds();
})();