const P={start:{name:'Старт · Nicolae Bălcescu',lat:45.79630,lng:24.15156},mare:{name:'Piața Mare',lat:45.79678,lng:24.15157},mary:{name:'Евангелический собор Св. Марии',lat:45.79777,lng:24.15008},bridge:{name:'Мост Лжецов + Piața Mică',lat:45.79832,lng:24.15080},stairs:{name:'Pasajul Scărilor → Lower Town',lat:45.79768,lng:24.14919},lower:{name:'Тихие улицы Lower Town',lat:45.79892,lng:24.14782},tower:{name:'Strada Cetății + башни',lat:45.79430,lng:24.15304},bruk:{name:'Дворец Брукенталя',lat:45.79655,lng:24.15066},holy:{name:'Православный собор Св. Троицы',lat:45.79459,lng:24.14812},astra:{name:'Parcul Astra',lat:45.79334,lng:24.14750},finish:{name:'Финиш · обратно к центру',lat:45.79630,lng:24.15156}};
const common=[
{id:'mare',n:1,title:P.mare.name,desc:'Быстрый круг по площади: барочные фасады, «глаза» на крышах, ратуша. Не зависай — дальше интереснее.',time:'10 мин',tag:'разминка'},
{id:'mary',n:2,title:P.mary.name,desc:'Зайди внутрь и поднимись в башню. Это лучший высокий вид в коротком маршруте.',time:'25–30 мин',tag:'вид сверху'},
{id:'bridge',n:3,title:P.bridge.name,desc:'Мост, арки, маленькая площадь. Сделай круг вокруг площади, а не только фото с моста.',time:'10–15 мин',tag:'икона Сибиу'},
{id:'stairs',n:4,title:P.stairs.name,desc:'Спускайся через старые стены и арки в Нижний город. Здесь Сибиу становится менее открыткой и больше живым средневековым городом.',time:'20 мин',tag:'атмосфера'}
];
const dry=[
{id:'lower',n:5,title:P.lower.name,desc:'Небольшая петля по Ocnei / Faurului: цветные дома, дворы, уклон улиц и виды обратно на верхний город.',time:'20 мин',tag:'без толпы'},
{id:'tower',n:6,title:P.tower.name,desc:'Резко меняем сторону центра: кусок городской стены, Turnul Dulgherilor и линия старых укреплений.',time:'20–25 мин',tag:'крепостная стена'},
{id:'holy',n:7,title:P.holy.name,desc:'Очень мощный интерьер в византийском духе. Зайди хотя бы на 10 минут — совсем другая архитектура после саксонского центра.',time:'15 мин',tag:'внутри'},
{id:'astra',n:8,title:P.astra.name,desc:'Спокойный зелёный финал. Если осталось время — кофе и обратно по Mitropoliei / Bălcescu.',time:'15–25 мин',tag:'финиш 14:40–15:00'}
];
const rain=[
{id:'bruk',n:5,title:P.bruk.name,desc:'Главная дождливая развилка: 45–60 минут внутри дворца и картинной галереи. Сегодня открыт 10:00–18:00.',time:'50–60 мин',tag:'сухо и красиво'},
{id:'holy',n:6,title:P.holy.name,desc:'После музея — короткий переход в православный собор. Держит маршрут визуально разнообразным.',time:'15 мин',tag:'внутри'},
{id:'astra',n:7,title:P.astra.name,desc:'Если дождь стих — 10 минут через парк; если нет, просто режь обратно к Bălcescu.',time:'10–20 мин',tag:'опционально'}
];
let mode=localStorage.getItem('sibiu-mode')||'dry';let completed=new Set(JSON.parse(localStorage.getItem('sibiu-done')||'[]'));
const map=L.map('map',{zoomControl:false,attributionControl:true}).setView([45.7963,24.1505],16);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);
let routeLine,userMarker,markers=[],lastPos=null;
const currentStops=()=>[...common,...(mode==='dry'?dry:rain)];
function markerIcon(n,branch,id){return L.divIcon({className:'',html:`<div class="marker ${branch?'branch':''} ${completed.has(id)?'done':''}">${n}</div>`,iconSize:[28,28],iconAnchor:[14,14]})}
function draw(){markers.forEach(m=>map.removeLayer(m));markers=[];if(routeLine)map.removeLayer(routeLine);const stops=currentStops();stops.forEach((s,i)=>{const p=P[s.id];markers.push(L.marker([p.lat,p.lng],{icon:markerIcon(s.n,i>=common.length,s.id)}).addTo(map).bindPopup(`<b>${s.n}. ${s.title}</b><br>${s.desc}`))});const pts=[P.start,...stops.map(s=>P[s.id]),P.finish].map(p=>[p.lat,p.lng]);routeLine=L.polyline(pts,{color:mode==='dry'?'#b7ff5f':'#a98bff',weight:5,opacity:.82,dashArray:mode==='dry'?null:'10 7'}).addTo(map);document.querySelectorAll('.routebtn').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));document.getElementById('modeLabel').textContent=mode==='dry'?'сухой маршрут':'дождевой маршрут';document.getElementById('routeSummary').textContent=mode==='dry'?'улицы · стены · 2:45':'Брукенталь · собор · 2:50';renderStops();updateGmaps();updateNext()}
function renderStops(){const root=document.getElementById('stops');root.innerHTML='';currentStops().forEach(s=>{const p=P[s.id],done=completed.has(s.id),el=document.createElement('article');el.className='stop'+(done?' done':'');el.innerHTML=`<div class="num">${done?'✓':s.n}</div><div><h3>${s.title}</h3><p>${s.desc}</p><div class="meta"><span>${s.time}</span><span>${s.tag}</span></div><a class="goto" target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=${p.lat},${p.lng}">точка в Google Maps ↗</a></div><input class="check" type="checkbox" ${done?'checked':''} aria-label="Готово">`;el.querySelector('.check').addEventListener('change',e=>{e.target.checked?completed.add(s.id):completed.delete(s.id);save();draw()});root.appendChild(el)})}
function save(){localStorage.setItem('sibiu-mode',mode);localStorage.setItem('sibiu-done',JSON.stringify([...completed]))}
function updateGmaps(){const ids=currentStops().map(s=>s.id),dest=P[ids.at(-1)],wps=ids.slice(0,-1).map(id=>`${P[id].lat},${P[id].lng}`).join('|');document.getElementById('gmaps').href=`https://www.google.com/maps/dir/?api=1&travelmode=walking&destination=${dest.lat},${dest.lng}&waypoints=${encodeURIComponent(wps)}`}
function km(a,b){const R=6371,dLat=(b.lat-a.lat)*Math.PI/180,dLon=(b.lng-a.lng)*Math.PI/180,x=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function updateNext(){const next=currentStops().find(s=>!completed.has(s.id));if(!next){document.getElementById('nextName').textContent='Маршрут пройден 🎉';document.getElementById('nextDist').textContent='можно спокойно идти за кофе';return}document.getElementById('nextName').textContent='Следующая: '+next.title;if(lastPos){const d=km(lastPos,P[next.id]);document.getElementById('nextDist').textContent=d<1?`${Math.round(d*1000)} м по прямой`:`${d.toFixed(1)} км по прямой`}}
function locate(){if(!navigator.geolocation){document.getElementById('nextDist').textContent='геолокация не поддерживается';return}navigator.geolocation.getCurrentPosition(pos=>{lastPos={lat:pos.coords.latitude,lng:pos.coords.longitude};if(userMarker)map.removeLayer(userMarker);userMarker=L.marker([lastPos.lat,lastPos.lng],{icon:L.divIcon({className:'',html:'<div class="userdot"></div>',iconSize:[18,18],iconAnchor:[9,9]})}).addTo(map).bindPopup('Ты здесь');map.setView([lastPos.lat,lastPos.lng],17);updateNext()},()=>document.getElementById('nextDist').textContent='разреши доступ к геопозиции',{enableHighAccuracy:true,timeout:8000})}
function tick(){const d=new Date();document.getElementById('now').textContent=d.toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'});const end=new Date(d);end.setHours(15,0,0,0);const min=Math.max(0,Math.round((end-d)/60000));document.getElementById('left').textContent=min?`до 15:00 · ${Math.floor(min/60)}ч ${min%60}м`:'15:00 уже наступило'}
document.querySelectorAll('.routebtn').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;save();draw()});document.getElementById('locate').onclick=locate;document.getElementById('fit').onclick=()=>map.fitBounds(routeLine.getBounds(),{padding:[24,24]});document.getElementById('reset').onclick=()=>{completed.clear();save();draw()};tick();setInterval(tick,30000);draw();setTimeout(()=>map.fitBounds(routeLine.getBounds(),{padding:[22,22]}),200);setTimeout(locate,700);