plugins {
    id 'com.android.application'
}

android {
    namespace 'com.tripatrip.tracker'
    compileSdk 35

    defaultConfig {
        applicationId 'com.tripatrip.romania.complete'
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName '3.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5'
}
